Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [b, conc_params]
 -- Processing LG18P
After dropping NA and 0-VAP, len df 6910 -> 6655
    -- Scaled 4 precincts, for an increase of 65 VAP
Running ['WVAP', 'BVAP', 'HVAP', 'OVAP'] x ['Mandela Barnes', 'Kurt Kober', 'None'] EI on LG18P
r = 4 rows (demographic groups)
c = 3 columns (candidates or voting outcomes)
number of precincts = 6655
â–ˆTraceback (most recent call last):
  File "ei.py", line 126, in <module>
    main()
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "ei.py", line 123, in main
    run_ei(state, elec, g, num_tunes, num_draws, county)
  File "ei.py", line 101, in run_ei
    ei.fit(group_fractions,
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/pyei/r_by_c.py", line 262, in fit
    self.sim_trace = pm.sample(
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/pymc3/sampling.py", line 545, in sample
    trace = _mp_sample(**sample_args, **parallel_args)
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/pymc3/sampling.py", line 1486, in _mp_sample
    for draw in sampler:
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/pymc3/parallel_sampling.py", line 492, in __iter__
    draw = ProcessAdapter.recv_draw(self._active)
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/site-packages/pymc3/parallel_sampling.py", line 357, in recv_draw
    msg = ready[0].recv()
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/cluster/home/gschoe01/miniconda3/envs/fake-ensemble-analysis/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

Making viz for LG18P on ('WVAP', 'BVAP', 'HVAP')...
Making summary for LG18P on ('WVAP', 'BVAP', 'HVAP')
slurmstepd: error: Detected 1 oom-kill event(s) in step 5706577.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
